site:
  title: Spring Framework
  url: https://docs.spring.io/spring-framework/reference
  robots: allow
git:
  ensure_git_suffix: false
content:
  sources:
  - url: ../../
    branches: main
    start_path: /framework-docs/ko/
asciidoc:
  extensions:
    - '@asciidoctor/tabs'
    - '@springio/asciidoctor-extensions'
    - '@springio/asciidoctor-extensions/include-code-extension'
  attributes:
    page-stackoverflow-url: https://stackoverflow.com/questions/tagged/spring
    page-pagination: ''
    hide-uri-scheme: '@'
    tabs-sync-option: '@'
    include-java: 'example$docs-src/main/java/org/springframework/docs'
urls:
  latest_version_segment_strategy: redirect:to
  latest_version_segment: ''
  redirect_facility: httpd
runtime:
  log:
    failure_level: warn
ui:
  bundle:
    url: https://github.com/spring-io/antora-ui-spring/releases/download/v0.4.25/ui-bundle.zip
